import type { TenantConfig } from "./types";

export const tenantRegistry: Record<string, TenantConfig> = {
  acme: {
    id: "tenant_acme_001",
    slug: "acme",
    displayName: "Acme Corporation",
    branding: {
      primaryColor: "#6366f1",
      secondaryColor: "#4f46e5",
      accentColor: "#a5b4fc",
      surfaceColor: "#1e1e2e",
      backgroundColor: "#13131f",
      textPrimaryColor: "#e2e8f0",
      textSecondaryColor: "#94a3b8",
      fontFamily: "'Inter', sans-serif",
      logoText: "ACME CMS",
      companyName: "Acme Corporation",
    },
    featureFlags: {
      collaborativeEditing: true,
      advancedAnalytics: true,
      mediaLibrary: true,
      multiLanguage: true,
      versionHistory: true,
      webhooks: true,
      apiAccess: true,
      customWorkflows: true,
      auditLog: true,
      ssoEnabled: true,
    },
    plan: {
      tier: "enterprise",
      maxUsers: 500,
      maxStorageGb: 1000,
      maxContentItems: 50000,
    },
    allowedDomains: ["acme.cms.com", "acme.internal"],
    defaultLocale: "en-US",
    supportedLocales: ["en-US", "de-DE", "fr-FR", "ja-JP"],
    timezone: "America/New_York",
    apiBaseUrl: "https://api.acme.cms.com",
  },
  globex: {
    id: "tenant_globex_001",
    slug: "globex",
    displayName: "Globex Media Group",
    branding: {
      primaryColor: "#10b981",
      secondaryColor: "#059669",
      accentColor: "#6ee7b7",
      surfaceColor: "#1a1f2e",
      backgroundColor: "#0f1520",
      textPrimaryColor: "#f1f5f9",
      textSecondaryColor: "#8492a6",
      fontFamily: "'Outfit', sans-serif",
      logoText: "GLOBEX",
      companyName: "Globex Media Group",
    },
    featureFlags: {
      collaborativeEditing: true,
      advancedAnalytics: true,
      mediaLibrary: true,
      multiLanguage: false,
      versionHistory: true,
      webhooks: false,
      apiAccess: true,
      customWorkflows: false,
      auditLog: true,
      ssoEnabled: false,
    },
    plan: {
      tier: "professional",
      maxUsers: 50,
      maxStorageGb: 100,
      maxContentItems: 5000,
    },
    allowedDomains: ["globex.cms.com"],
    defaultLocale: "en-GB",
    supportedLocales: ["en-GB", "es-ES"],
    timezone: "Europe/London",
    apiBaseUrl: "https://api.globex.cms.com",
  },
};
