[build]
  command = "pnpm install && pnpm turbo run build --filter=@cms/analytics"
  publish = "apps/analytics/out"
  base    = "."

[build.environment]
  NODE_VERSION = "20.11.0"
  PNPM_VERSION = "9.1.0"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
