[build]
  command = "pnpm install && pnpm turbo run build --filter=@cms/settings"
  publish = "apps/settings/dist"
  base    = "."

[build.environment]
  NODE_VERSION = "20.11.0"
  PNPM_VERSION = "9.1.0"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

[[headers]]
  for    = "/remoteEntry.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for    = "/*.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
